// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts` (hash: 317b526da4feed5ffa3c3ce8216843cc)
// Runtime types generated with workerd@1.20250320.0 2025-02-14 nodejs_compat
declare namespace Cloudflare {
	interface Env {
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
